### ISSUE TITLE
CI for GHC 8.10

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#145]
Once staging is merged, will Plutarch continue to support GHC 8.10?

I think it should, because not all smart contracts will be moving over to GHC 9.2.

**Comment by L-as** [comment]
I think yes, and AFAICT the core library should still compile fine, even if the tests don't.

**Comment by TotallyNotChase** [comment]
So, when using the `flake.nix` from [this PR](https://github.com/mlabs-haskell/plutus-scaffold/pull/17), and changing `ghcVersion` to `ghc8107` - I seem to be getting compile errors for fourmolu during `nix develop`-
```
src/Ormolu/Utils/Extensions.hs:24:1: error:
    Could not find module ‘Distribution.Utils.Path’
    Perhaps you meant
      Distribution.Utils.IOData (from Cabal-3.2.1.0)
      Distribution.Utils.MD5 (from Cabal-3.2.1.0)
      Distribution.Utils.Base62
```
is it expecting a more up to date cabal version?

**Comment by TotallyNotChase** [comment]
FWIW I did get that flake and everything to work with 8.10.7 by removing fourmolu.

**Comment by srid** [comment]
@TotallyNotChase Why not modify Plutarch's `flake.nix`? Did you notice it requiring more than compiler version change?

**Comment by TotallyNotChase** [comment]
¯\_(ツ)_/¯ I'm just not very good with nix. It works flawlessly on my testbed with ghc8107 after removing fourmolu. I'm sure you could make it work with fourmolu as well by modifying the nix a bit.

**Comment by srid** [comment]
For the record, it only requires changing compiler version, removing fourmolu/ format checks and adding back HLS.

Diff: https://github.com/Plutonomicon/plutarch/compare/staging...srid/ghc8107

Everything but the examples build:

https://hercules-ci.com/github/Plutonomicon/plutarch/jobs/353

I wonder if all of this can be parameterized so we can do `nix develop` using either of the compilers.

**Comment by L-as** [comment]
I think we should at the very least in CI make sure compilation with GHC 8.10.7 works.

**Comment by L-as** [comment]
I changed the name of the issue.

**Comment by srid** [comment]
#188 adds CI for the library, but we are not running tests.

**Comment by L-as** [comment]
The tests can't be run. They depend on GHC 9.2.1.

**Comment by blamario** [comment]
Only a couple of test suites depend on GHC 9, Fields and API I think. We could guard them in `examples/Main.hs` with `#if MIN_VERSION_GLASGOW_HASKELL(9,1)`.

**Comment by L-as** [comment]
@blamario Do you know of a way to check for GHC version in `plutarch.cabal`?

**Comment by blamario** [comment]
https://cabal.readthedocs.io/en/3.4/cabal-package.html#conditions

`if impl(ghc >= 9.0)` should do it.

**Comment by L-as** [comment]
I didn't know you could do that!

**Comment by srid** [comment]
8.10 generates a slightly different error for pattern match failures, and that broke one golden test:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/3998/154117898-83a6c17c-27d6-4edd-b474-88b998257840.png">

**Comment by TotallyNotChase** [comment]
I'm starting to think most compilation outputs are rather flaky

**Comment by srid** [comment]
At least it is flakiness across space (ghc versions) rather than flakiness across time. The latter being non-deterministic is the annoying one.

**Comment by srid** [comment]
This also happens in 8.10 (but not 9.2):

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3998/154135160-33df1be3-31e2-47c2-a976-fa90f973d1bf.png">
